export enum JoinRestriction {
    ANYONE = "ANYONE",
    LOW_INCOME_ONLY = "LOW_INCOME_ONLY",
    PARTIAL = "PARTIAL",
}
export enum ReserveType {
    FIXED = "FIXED",
    FREE = "FREE",
}
export enum InterestCalcType {
    SIMPLE = "SIMPLE",
    COMPOUND = "COMPOUND",
}
export enum ConditionStatus {
    EXTRACTED = "EXTRACTED",
    PENDING = "PENDING",
    FAILED = "FAILED",
    NEEDS_REVIEW = "NEEDS_REVIEW",
}
export enum CatalogMessages {
    TITLE = "전체 적금 상품",
    HELP = "공시된 상품을 모두 보여드려요. 최고금리는 우대조건을 모두 충족했을 때의 금리예요.",
    LOADING = "상품 정보를 불러오고 있어요.",
    LOAD_ERROR = "상품 정보를 불러오지 못했어요. 다시 시도해 주세요.",
    MISSING = "해당 상품을 찾을 수 없어요.",
    MAX_RATE = "공시 최고금리",
    NO_DISCLOSURE = "미공시",
    LIST_BACK = "전체 상품으로",
    NO_RATE = "공시된 금리 옵션이 없어요.",
    CHECKLIST_EMPTY = "추가로 등록된 체크리스트가 없어요. 각 탭에서 공시 원문을 확인해 주세요.",
    CONDITION_PENDING = "상품 조건 확인이 완료되지 않았어요. 가입 자격과 우대조건은 공시 원문을 확인해 주세요.",
    DETAIL_INCOMPLETE = "추가 공시 정보를 불러오지 못했어요. 저장된 비교 결과를 보여드려요.",
    PERIOD_RATES = "기간별 금리",
    DISCLOSURE_PRETAX = "공시 기준 · 세전",
    TERM = "기간",
    RESERVE = "적립",
    CALCULATION = "계산",
    BASE = "기본",
    MAXIMUM = "최고",
    FIXED = "정액",
    FREE = "자유",
    SIMPLE = "단리",
    COMPOUND = "복리",
    MEMBER = "가입 대상",
    RESTRICTION = "가입 제한",
    ANYONE = "제한 없음",
    LOW_INCOME = "서민 전용 · 자격 확인 필요",
    PARTIAL = "일부 제한 · 자격 확인 필요",
    JOIN_WAYS = "가입 경로",
    LIMIT = "월 납입 한도",
    MATURITY = "만기 후 금리",
    NOTE = "유의사항",
    DISCLOSURE_MONTH = "공시 기준월",
    DISCLOSURE_DATE = "공시 시작일",
    CONTACT = "문의",
    JOIN_LINK = "가입하러 가기 ↗",
    JOIN_LINK_NOTICE = "공식 홈페이지가 새 창으로 열려요. 가입은 은행에서 진행돼요.",
    FOOTNOTE = "금융감독원 공시 기준이에요. 최종 가입 가능 여부와 금리는 은행 상품설명서를 확인해 주세요.",
}
