export enum EligibilityStatus {
    ELIGIBLE = "ELIGIBLE",
    NEEDS_CONFIRMATION = "NEEDS_CONFIRMATION",
    NOT_ELIGIBLE = "NOT_ELIGIBLE",
}
export enum EstimateStatus {
    ESTIMATED = "ESTIMATED",
    AMOUNT_REQUIRED = "AMOUNT_REQUIRED",
    INVALID_AMOUNT = "INVALID_AMOUNT",
    MONTHLY_LIMIT_EXCEEDED = "MONTHLY_LIMIT_EXCEEDED",
    INELIGIBLE = "INELIGIBLE",
    CHECK_REQUIRED = "CHECK_REQUIRED",
}
export enum GoalReachStatus {
    NO_GOAL = "NO_GOAL",
    REACHED = "REACHED",
    REACHED_AT_MAX_RATE = "REACHED_AT_MAX_RATE",
    SHORT = "SHORT",
}
export enum ComparisonViewStatus {
    READY = "READY",
    LOADING = "LOADING",
    ERROR = "ERROR",
    NO_OPTION = "NO_OPTION",
}
export enum ComparisonMessages {
    TITLE = "예상 만기금액 확인",
    MONTHLY = "월 납입액",
    MONTHLY_INPUT = "월 납입액 (원)",
    MONTHLY_NOT_ANSWERED = "월 납입액을 답하지 않아 예상금액을 계산하지 않았어요.",
    MONTHS = "가입 기간",
    SUBMIT = "예상금액 확인",
    DEFAULT_TERM = "기간을 선택하지 않으면 12개월 기준으로 보여드려요.",
    ASSUMPTION = "매월 같은 금액을 납입하는 세전 예상금액이에요. 실제 납입일과 은행 계산 방식에 따라 달라질 수 있어요.",
    LOADING = "가입 조건과 예상금액을 확인하고 있어요.",
    ERROR = "개인별 비교 정보를 불러오지 못했어요. 상품 정보는 계속 확인할 수 있어요.",
    RETRY = "비교정보 다시 확인",
    REFRESH = "비교정보 갱신",
    NO_OPTION = "선택한 기간의 금리 옵션이 없어요. 다른 기간을 확인해 주세요.",
    ELIGIBLE = "가입 가능",
    NEEDS_CONFIRMATION = "조건 확인 필요",
    NOT_ELIGIBLE = "가입 불가",
    ELIGIBLE_HELP = "입력한 답변과 확인된 공시 조건 기준이에요.",
    CONDITIONAL_RATE = "답변 기준 금리",
    CONFIRMED_RATE = "내 확인 금리",
    REJECTED_HELP = "입력한 조건으로는 가입할 수 없어 예상금액을 표시하지 않아요.",
    MATURITY = "예상 만기금액 · 세전",
    MATURITY_AT_MAX = "최대 조건 충족 시",
    MATURITY_MINE = "내 기준",
    PRINCIPAL = "원금",
    INTEREST = "예상 이자 · 세전",
    AMOUNT_REQUIRED = "월 납입액을 입력하면 예상 만기금액을 확인할 수 있어요.",
    MY_RATE_LABEL = "내가 받을 금리",
    GOAL_REACHED = "내 기준으로",
    GOAL_REACHED_AT_MAX_RATE = "우대조건을 모두 채우면",
    GOAL_SHORT = "목표 금액까지",
    ALL_BANKS = "전체",
    CATEGORIES = "은행별 상품 카테고리",
    SWIPE_HELP = "좌우로 밀어 은행별 상품을 확인해 보세요.",
    OPTION = "적립 · 이자 계산 방식",
    OPTION_RULE = "같은 기간에서는 확인 금리가 높은 옵션을 먼저 보여드려요. 금리가 같으면 정액·단리 순이에요.",
    COMPARISON_UNAVAILABLE = "비교 옵션을 확인할 수 없어요. 비교정보를 다시 확인해 주세요.",
}
